CREATE TABLE IF NOT EXISTS cfg_app_test_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    adb_path VARCHAR(500) NOT NULL DEFAULT 'adb' COMMENT 'ADB路径',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='APP测试配置表';

INSERT INTO cfg_app_test_config (adb_path) VALUES ('adb');
