CREATE TABLE IF NOT EXISTS cfg_dify_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    api_url VARCHAR(500) NOT NULL COMMENT 'Dify API URL',
    api_key VARCHAR(500) NOT NULL COMMENT 'Dify API Key',
    is_enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    is_deleted TINYINT(1) DEFAULT 0 COMMENT '逻辑删除',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Dify配置表';
