CREATE TABLE IF NOT EXISTS testcase_generation_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    requirement_text TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    progress INT DEFAULT 0,
    output_mode VARCHAR(10) DEFAULT 'stream',
    stream_buffer LONGTEXT,
    stream_position INT DEFAULT 0,
    last_stream_update DATETIME,
    project_id BIGINT,
    writer_model_config_id BIGINT,
    reviewer_model_config_id BIGINT,
    writer_prompt_config_id BIGINT,
    reviewer_prompt_config_id BIGINT,
    generated_test_cases LONGTEXT,
    review_feedback LONGTEXT,
    final_test_cases LONGTEXT,
    generation_log LONGTEXT,
    error_message TEXT,
    created_by BIGINT NOT NULL,
    is_saved_to_records TINYINT(1) DEFAULT 0,
    saved_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at DATETIME,
    INDEX idx_task_id (task_id),
    INDEX idx_status (status),
    INDEX idx_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
